# Program untuk daftar nama produk beserta nama merek dan harganya
# String 1
nama = "Buku"
merek = "Sidu"
harga = "5.000"
hasil_stringb = "Nama:" + nama + ", Merek:" + merek + ", Harga:" + harga
# String 2
nama = "pulpen"
merek = "Joyko"
harga = "4.000"
hasil_string1 = "Nama:" + nama + ", Merek:" + merek + ",Harga:" + harga
#String3
nama = "Tip_x"
merek = "Joyko"
harga = "3.000"
hasil_string2 = "Nama:" + nama + ", Merek" + merek + ",Harga:" + harga
print("Daftar produk:",hasil_stringb)
print("Daftar produk:",hasil_string1)
print("Daftar produk:", hasil_string2)